### ISSUE TITLE
Support TypeScript 4 and up

### ISSUE THREAD

**Issue by yokuze** [silvermine/eslint-config-silvermine#76]
We will not be able to lint TypeScript projects that use versions greater than 3.9 until we update the `@typescript-eslint/parser` package so that it can parse newer TypeScript syntax. Most of our projects are using TypeScript 3.9. As of this writing, the latest stable TypeScript version is v4.6.3.

While it seems it's possible to update `@typescript-eslint/parser` without also updating ESLint, we should probably also update ESLint to the latest version while we are at it.

**Comment by onebytegone** [comment]
Resolved with https://github.com/silvermine/eslint-config-silvermine/pull/77
